---
- name: install bind9
  ansible.builtin.apt:
    name: bind9
    state: present
    update_cache: yes

- name: compute dns values
  ansible.builtin.set_fact:
    reverse_dns_base: '{{ [2, 1, 0] | map("extract", hostvars["dns-server1"].ansible_host | split(".")) | list | join(".") }}'
    reverse_dns_prefix: '{{ hostvars["dns-server1"].ansible_host | split(".") | first }}'

- name: copy bind9 primary config
  when: ansible_hostname == "dns-server1"
  ansible.builtin.template:
    src: named.conf.local-primary.j2
    dest: /etc/bind/named.conf.local
  register: named_config

- name: copy bind9 secondary config
  when: ansible_hostname == "dns-server2"
  ansible.builtin.template:
    src: named.conf.local-secondary.j2
    dest: /etc/bind/named.conf.local
  register: named_config

- name: copy cluster zone
  ansible.builtin.template:
    src: db.cluster.local.j2
    dest: /etc/bind/db.cluster.local
  register: cluster_zone_config

- name: copy cluster reverse zone
  ansible.builtin.template:
    src: db.cluster.local.j2
    dest: '/etc/bind/db.{{ reverse_dns_prefix }}'
  register: cluster_reverse_zone_config

- name: copy apps zone
  template:
    src: db.apps.local.j2
    dest: '/etc/bind/db.{{ apps_domain }}'
  register: apps_zone_config

- name: restart named
  when: named_config.changed or
        cluster_zone_config.changed or
        cluster_reverse_zone_config.changed or
        apps_zone_config.changed
  ansible.builtin.systemd:
    name: named
    state: restarted
    enabled: yes