---
- name: agent token
  ansible.builtin.set_fact:
    consul_agent_token: '{{ inventory_hostname | to_uuid }}'

- name: copy consul config
  template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
  register: consul_config

- name: restart consul
  when: consul_config.changed
  service:
    name: consul
    state: restarted
    enabled: yes

# consul acl bootstrap

# - name: bootstrap consul acl
#   run_once: true
#   ansible.builtin.command:
#     cmd: consul acl bootstrap -format=json
#   register: acl_bootstrap_result
#   failed_when:
#     - acl_bootstrap_result.rc != 0
#     - '"ACL bootstrap no longer allowed" not in acl_bootstrap_result.stderr'
#   changed_when:
#     - '"SecretID" in acl_bootstrap_result.stdout'

# - name: save consul acl bootstrap json file
#   when: acl_bootstrap_result.changed
#   run_once: true
#   delegate_to: localhost
#   ansible.builtin.copy:
#     content: "{{ acl_bootstrap_result.stdout }}"
#     dest: consul_acl_bootstrap.json

# - name: generate agent token
#   ansible.builtin.command:
#     cmd: "consul acl token create -token='{{ consul_management_token }}' -secret='{{ consul_agent_token }}' -description='{{ inventory_hostname }}' -node-identity='{{ inventory_hostname }}:dc1' -format=json"
#   register: agent_token_result
