---
- name: Create consul client certs dir
  ansible.builtin.file:
    path: /etc/certs.d/consul
    state: directory

- name: Copy consul client certs
  loop: ["cert", "private_key"]
  ansible.builtin.copy:
    content: '{{ consul_client_certs[item] }}'
    dest: '/etc/certs.d/consul/{{ item }}.pem'
    owner: consul
    mode: 0644

- name: Define agent token
  ansible.builtin.set_fact:
    consul_agent_token: '{{ ("agent." + inventory_hostname) | to_uuid(namespace="6ba7b810-9dad-11d1-80b4-00c04fd430c8") }}'

- name: Create agent token
  delegate_to: consul-server1
  ansible.builtin.command:
    consul acl token create
      -http-addr https://localhost:8501
      -ca-file /etc/certs.d/ca.pem
      -client-cert /etc/certs.d/cert.pem
      -client-key /etc/certs.d/private_key.pem
      -token "{{ consul_management_token }}"
      -description "{{ ansible_hostname }} agent token"
      -node-identity "{{ ansible_hostname }}:dc1"
      -secret "{{ consul_agent_token }}"
  register: create_agent_token
  failed_when:
    - create_agent_token.rc != 0
    - '"SecretID is already in use" not in create_agent_token.stderr'
  changed_when: create_agent_token.rc == 0

- name: Copy consul config
  ansible.builtin.template:
    src: consul.hcl.j2
    dest: /etc/consul.d/consul.hcl
    owner: consul
    mode: 0644
  register: consul_config

- name: Restart consul
  when: consul_config.changed
  ansible.builtin.systemd:
    name: consul
    state: restarted
    enabled: true

- name: Copy systemd-resolved consul config
  ansible.builtin.copy:
    src: consul.conf
    dest: /etc/systemd/resolved.conf.d/
    mode: 0644
  register: resolved_config

- name: Restart systemd-resolved
  when: resolved_config.changed
  ansible.builtin.systemd:
    name: systemd-resolved
    state: restarted

