- name: Setup load balancer
  hosts: load-balancer
  tasks:
    - name: Include ca certificate
      ansible.builtin.import_tasks: '{{ playbook_dir }}/../../tasks/ca-cert/tasks.yaml'

    - name: Setup dns client
      ansible.builtin.import_tasks: '{{ playbook_dir }}/../../tasks/dns-client/tasks.yaml'

    - name: Copy nomad cert with private key combined
      ansible.builtin.copy:
        content: '{{ nomad_client_certs["private_key"] }}{{ nomad_client_certs["cert"] }}'
        dest: '/etc/certs.d/nomad_server.crt'
        mode: 0644

    - name: Install HAProxy
      ansible.builtin.apt:
        name: haproxy
        state: present
        update_cache: true

    - name: Copy haproxy config
      ansible.builtin.template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg
        owner: haproxy
        mode: 0644
      notify: Restart haproxy

  handlers:
    - name: Restart haproxy
      ansible.builtin.systemd:
        name: haproxy
        state: restarted
        enabled: true
