---

- name: copy nomad config
  ansible.builtin.copy:
    src: nomad.hcl
    dest: /etc/nomad.d/nomad.hcl
  register: nomad_config

- name: restart nomad
  when: nomad_config.changed
  ansible.builtin.service:
    name: nomad
    state: restarted
    enabled: true

# nomad acl bootstrap

- name: bootstrap nomad acl
  run_once: true
  ansible.builtin.command:
    cmd: nomad acl bootstrap -json
  register: acl_bootstrap_result
  failed_when:
    - acl_bootstrap_result.rc != 0
    - '"ACL bootstrap already done" not in acl_bootstrap_result.stderr'
  changed_when:
    - '"SecretID" in acl_bootstrap_result.stdout'

- name: save nomad acl bootstrap json file
  when: acl_bootstrap_result.changed
  run_once: true
  delegate_to: localhost
  ansible.builtin.copy:
    content: "{{ acl_bootstrap_result.stdout }}"
    dest: nomad_acl_bootstrap.json
